---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LD_PRELOAD: ""
  RUST_VERSION: 1.46.0

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /dbg\//
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /dev\// && $CI_COMMIT_TITLE =~ /WIP/
      when: never
    - when: always

# unstable, yeah !
image: simgrid/unstable:latest

stages:
  - build1
  - build2
  - test


###############################################################################
#
# Build Qemu patched for Tansiv
#   -- test locally:
#      $) gitlab-runner exec docker qemu
#
###############################################################################
qemu:
  stage: build1
  script:
    #
    # Some missing build tools
    #
    - apt-get update
    - apt-get install -y build-essential git pkg-config libglib2.0-dev libpixman-1-dev
    #
    - git clone --depth 1 https://gitlab.inria.fr/msimonin/qemu.git -b tantap src/qemu
    - cd src/qemu
    - ./configure && make config-host.h
  artifacts:
    paths:
      - src/qemu


###############################################################################
#
# Build tansiv and some cppunit stuffs
#   -- test locally:
#      $) gitlab-runner exec docker tansiv
#
###############################################################################
tansiv:
  stage: build2
  script:
    #
    # Some missing build tools
    #
    - apt-get update
    - apt-get install -y curl git build-essential pkg-config libboost-dev cmake libcppunit-dev libglib2.0-dev clang libclang-dev
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init
    - sh rustup-init -y --profile minimal --default-toolchain $RUST_VERSION
    - export PATH=$HOME/.cargo/bin:$PATH
    #
    # Build tests
    # TODO(msimonin): make all (but we'll need to adapt all vsg clients ...)
    #
    - mkdir -p build
    - cd build
    - cmake .. && make
    # unittests
    # NOTE(msimonin): as long as https://gitlab.inria.fr/quinson/2018-vsg/-/issues/5 is around
    # we run our tests isolated in different process.
    # This is far from ideal since reports will be spread in the output of each process
    # But at least catch2 lets use specify this easily...
    # But ...
    #   for some reason this fails: ./tests --list-test-names-only | xargs -d "\n" -n 1 ./tests
    #   grrr!
    - ./tests "VSG receive one message"
    - ./tests "VSG deliver one message"
    - ./tests "VSG send piggyback port"
    - ./tests "piggyback port"
  artifacts:
    paths:
      - build
    # expected /opt structure:
    # /opt
    #   examples/ -> compiled examples
    #   platform/ -> some simgrid plaform files
    #   tansiv/ -> result of tansiv make install (include + lib + bin)
    #   qemu/ -> result of qemu make install (include + lib + bin)


###############################################################################
#
# Build fake-vm
#   -- test locally:
#      $) gitlab-runner exec docker fake-vm --docker-volumes $(pwd)/opt:/opt
#
###############################################################################
fake-vm:
  stage: build2
  image: rust:${RUST_VERSION}-slim-buster
  script:
  - apt-get update
  - apt-get install -y build-essential pkg-config libglib2.0-dev clang
  - cd src/fake-vm
  - make build
  - make test

###############################################################################
#
# Dummy ping/pong example
# inputs:
#   opt/ -> artifact of the build phase
#
###############################################################################
send:
  stage: test
  script:
    - cd build
    - ./tansiv examples/send/nova_cluster.xml examples/send/deployment.xml
