---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  RUST_VERSION: 1.42.0

# unstable, yeah !
image: simgrid/unstable:latest

stages:
  - build
  - test

###############################################################################
#
# Build tansiv and some cppunit stuffs
#   -- test locally:
#      $) gitlab-runner exec docker tansiv
#
###############################################################################
tansiv:
  stage: build
  script:
    #
    # Some missing build tools
    #
    - apt-get update
    - apt-get install -y curl git build-essential pkg-config libboost-dev cmake libcppunit-dev
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init
    - sh rustup-init -y --profile minimal --default-toolchain $RUST_VERSION
    - export PATH=$HOME/.cargo/bin:$PATH
    #
    # Build tests
    # TODO(msimonin): make all (but we'll need to adapt all vsg clients ...)
    #
    - mkdir -p build
    - cd build
    - cmake .. && make
    # cpp unittests
    - ./tests
  artifacts:
    paths:
      - build
    # expected /opt structure:
    # /opt
    #   examples/ -> compiled examples
    #   platform/ -> some simgrid plaform files
    #   tansiv/ -> result of tansiv make install (include + lib + bin)
    #   qemu/ -> result of qemu make install (include + lib + bin)


###############################################################################
#
# Build fake-vm
#   -- test locally:
#      $) gitlab-runner exec docker fake-vm --docker-volumes $(pwd)/opt:/opt
#
###############################################################################
fake-vm:
  stage: build
  image: rust:1.42.0-slim-buster
  script:
  - apt-get update
  - apt-get install -y build-essential
  - cd src/fake-vm
  - make build
  - make test

###############################################################################
#
# Dummy ping/pong example
# inputs:
#   opt/ -> artifact of the build phase
#
###############################################################################
send:
  stage: test
  script:
    - cd build
    - ./tansiv examples/send/nova_cluster.xml examples/send/deployment.xml
