[workspace]
members = ["tansiv-client", "capi", "tanproc", "tanproc_capi", "tanqemu", "tanqemu_capi", "tanqemukvm", "tanqemukvm_capi", "tandocker"]
default-members = ["tanproc_capi", "tanqemu_capi", "tanqemukvm_capi", "tandocker"]
